volumes:
    prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - "--web.enable-otlp-receiver"
    ports:
      - 9090:9090
    restart: always

  perses:
    image: persesdev/perses
    container_name: perses
    command: "--config=/etc/perses/config/config.yaml"
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./perses/config.yaml:/etc/perses/config/config.yaml
      - ./perses/project.yaml:/etc/perses/resources/project/project.yaml
      - ./built:/etc/perses/resources/dashboard
