volumes:
    prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      # - "--web.enable-otlp-receiver"
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - otel-collector

  perses:
    image: persesdev/perses
    container_name: perses
    command: "--config=/etc/perses/config/config.yaml"
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./perses/config.yaml:/etc/perses/config/config.yaml
      - ./perses/project.yaml:/etc/perses/resources/project/project.yaml
      - ./built:/etc/perses/resources/dashboard

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./otelcol/otel-collector-config.yml:/etc/otelcol/config.yaml
    command: ["--config=/etc/otelcol/config.yaml"]
    ports:
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 4318:4318 # OTLP http receiver
    restart: always

