#!/bin/sh

env OTEL_PHP_AUTOLOAD_ENABLED=true \
    OTEL_RESOURCE_ATTRIBUTES="service.instance.id=t3-demo" \
    OTEL_METRIC_EXPORT_INTERVAL=10000 \
    OTEL_TRACES_EXPORTER=none \
    OTEL_LOGS_EXPORTER=none \
    OTEL_METRICS_EXPORTER=otlp \
    OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf \
    OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://127.0.0.1:9090/api/v1/otlp/v1/metrics \
    OTEL_PROPAGATORS=baggage,tracecontext \
    OTEL_PHP_AUTOLOAD_ENABLED=true \
    OTEL_SERVICE_NAME=typo3-demo \
    GS_EXPORTER=none \
    php -S 10.0.0.55:7777
